Region_Example1 = 'Region_Example1'
Node_Example1_dataExample = 'Node_dataExample'
Node_Example1_handleExample = 'Node_handleExample'
Region_Example2 = 'Region_Example2'
Node_Example2_dataExample = 'Node_dataExample'
Node_Example2_handleExample = 'Node_handleExample'
